#!/bin/bash
SCRIPT_PATH=${0%/*}
if [ "$0" != "$SCRIPT_PATH" ] && [ "$SCRIPT_PATH" != "" ]; then 
    cd $SCRIPT_PATH
fi
cif2pha_DebUsSy magnetite.cif magnetite.pha
DB_PHA_CLU_x1.0 magnetite.ddb
MK_CELL_x1.0 
MK_BALL_x1.0 
Debussy Fe3O4.dwa
read -rn1

